#!/usr/bin/env bash
# ---------------------------------------------------------------------------- #
#            Apache 2.0 License Copyright (c) 2022 The Aurae Authors           #
#                                                                              #
#                ┏--------------------------------------------┓                #
#                ┃  █████╗ ██╗   ██╗██████╗  █████╗ ███████╗  ┃                #
#                ┃  ██╔══██╗██║   ██║██╔══██╗██╔══██╗██╔════╝ ┃                #
#                ┃  ███████║██║   ██║██████╔╝███████║█████╗   ┃                #
#                ┃  ██╔══██║██║   ██║██╔══██╗██╔══██║██╔══╝   ┃                #
#                ┃  ██║  ██║╚██████╔╝██║  ██║██║  ██║███████╗ ┃                #
#                ┃  ╚═╝  ╚═╝ ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝╚══════╝ ┃                #
#                ┗--------------------------------------------┛                #
#                                                                              #
#                         Distributed Systems Runtime                          #
#                                                                              #
# ---------------------------------------------------------------------------- #
#                                                                              #
#   Licensed under the Apache License, Version 2.0 (the "License");            #
#   you may not use this file except in compliance with the License.           #
#   You may obtain headers-check copy of the License at                        #
#                                                                              #
#       http://www.apache.org/licenses/LICENSE-2.0                             #
#                                                                              #
#   Unless required by applicable law or agreed to in writing, software        #
#   distributed under the License is distributed on an "AS IS" BASIS,          #
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   #
#   See the License for the specific language governing permissions and        #
#   limitations under the License.                                             #                                                                             #
#                                                                              #
# ---------------------------------------------------------------------------- #
#
set -e
# certgen-client assumes certgen has been ran

if [ -z "$1" ]; then
    echo "Usage: ./hack/certgen-client <name>"
    exit 1
fi
NAME=$1
echo " -> Generating Client: ${NAME}..."

## Generate client material
echo " -> Generating Client Material: client.${NAME}.key.pem, client.${NAME}.crt.pem..."
openssl genrsa -out "./pki/client.${NAME}.key.pem" 4096 2>/dev/null
openssl req \
  -new \
  -subj   "/C=IS/ST=Reykjavík/L=Reykjavík/O=Aurae/OU=Runtime/CN=client.${NAME}.unsafe.aurae.io" \
  -key "./pki/client.${NAME}.key.pem" \
  -out "./pki/client.${NAME}.crt.pem" 2>/dev/null

## Sign the client cert using the CA
echo " -> Signing Client Material (Root CA): client.${NAME}.crt.pem..."
openssl x509 \
  -req \
  -days   9999 \
  -in     "./pki/client.${NAME}.crt.pem" \
  -CA     "./pki/ca.crt.pem" \
  -CAkey  "./pki/ca.key.pem" \
  -CAcreateserial \
  -out "./pki/_signed.client.${NAME}.crt.pem" 2>/dev/null

## Verify the client material is signed
echo " -> Verify Client Material (Root CA): client.${NAME}.crt.pem..."
openssl verify -CAfile "./pki/ca.crt.pem" "./pki/_signed.client.${NAME}.crt.pem" 1>/dev/null && echo " -> Root Verification: Success!"
