#!/usr/bin/env bash
# ---------------------------------------------------------------------------- #
#             Apache 2.0 License Copyright © 2022 The Aurae Authors            #
#                                                                              #
#                +--------------------------------------------+                #
#                |   █████╗ ██╗   ██╗██████╗  █████╗ ███████╗ |                #
#                |  ██╔══██╗██║   ██║██╔══██╗██╔══██╗██╔════╝ |                #
#                |  ███████║██║   ██║██████╔╝███████║█████╗   |                #
#                |  ██╔══██║██║   ██║██╔══██╗██╔══██║██╔══╝   |                #
#                |  ██║  ██║╚██████╔╝██║  ██║██║  ██║███████╗ |                #
#                |  ╚═╝  ╚═╝ ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝╚══════╝ |                #
#                +--------------------------------------------+                #
#                                                                              #
#                         Distributed Systems Runtime                          #
#                                                                              #
# ---------------------------------------------------------------------------- #
#                                                                              #
#   Licensed under the Apache License, Version 2.0 (the "License");            #
#   you may not use this file except in compliance with the License.           #
#   You may obtain a copy of the License at                                    #
#                                                                              #
#       http://www.apache.org/licenses/LICENSE-2.0                             #
#                                                                              #
#   Unless required by applicable law or agreed to in writing, software        #
#   distributed under the License is distributed on an "AS IS" BASIS,          #
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   #
#   See the License for the specific language governing permissions and        #
#   limitations under the License.                                             #
#                                                                              #
# ---------------------------------------------------------------------------- #
#
set -e
echo ""

# The certgen script will create the following files in
# the /pki directory.
#
# -----------------------------------------------------
# pki/
# ├── aurae.ed25519.key
# ├── ca.crt
# ├── ca.crt.srl
# ├── ca.key
# ├── client.nova.crt                                                     
# ├── client.nova.key                                                     
# ├── client.system.crt                                                   
# ├── client.system.key                                                   
# ├── client.unsafe.crt                                                   
# ├── client.unsafe.key                                                   
# ├── server.crt                                                          
# ├── server.key                                                          
# ├── _signed.client.nova.crt                                             
# ├── _signed.client.system.crt                                           
# ├── _signed.client.unsafe.crt                                           
# └── _signed.server.crt     
# -----------------------------------------------------                                          
# Generate a ed25519 private key
echo " -> Generating Aurae ED25519 Key: aurae.ed25519.key..."
openssl genpkey -algorithm ED25519 > ./pki/aurae.ed25519.key

## Generate a root CA
echo " -> Generating Root CA From Aurae.ed25519.key: ca.key, ca.crt..."
openssl req \
  -new \
  -x509 \
  -nodes \
  -days    9999 \
  -addext "subjectAltName = DNS:localhost" \
  -subj    "/C=IS/ST=Reykjavík/L=Reykjavík/O=Aurae/OU=Runtime/CN=unsafe.aurae.io" \
  -keyout  "./pki/ca.key" \
  -out     "./pki/ca.crt" 2>/dev/null
  ## TODO Add -key ./pki/aurae.ed25519.key to use the ed25519 key

## Generate server material
echo " -> Generating Server Material: server.key, server.crt..."
openssl genrsa -out ./pki/server.key 4096 2>/dev/null
openssl req \
  -new \
  -addext "subjectAltName = DNS:localhost" \
  -subj   "/C=IS/ST=Reykjavík/L=Reykjavík/O=Aurae/OU=Runtime/CN=server.unsafe.aurae.io" \
  -key    "./pki/server.key" \
  -out    "./pki/server.crt" 2>/dev/null

## Sign the server cert using the CA
echo " -> Signing Server Material (Root CA): server.crt..."
openssl x509 \
  -req \
  -days   9999 \
  -in     "./pki/server.crt" \
  -CA     "./pki/ca.crt" \
  -CAkey  "./pki/ca.key" \
  -CAcreateserial \
  -out "./pki/_signed.server.crt" 2>/dev/null

## Verify the server material is signed
echo " -> Verify Server Material (Root CA): server.crt..."
openssl verify -CAfile "./pki/ca.crt" "./pki/_signed.server.crt" 1>/dev/null && echo " -> Root Verification: Success!"

# Client <nova>
. ./hack/certgen-client nova

# Client <unsafe>
. ./hack/certgen-client unsafe

# Client <system>
. ./hack/certgen-client system

echo ""
