#!/usr/bin/env bash
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ #
#            Apache 2.0 License Copyright (c) 2022 The Aurae Authors           #
#                                                                              #
#                ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓                #
#                ┃  █████╗ ██╗   ██╗██████╗  █████╗ ███████╗  ┃                #
#                ┃  ██╔══██╗██║   ██║██╔══██╗██╔══██╗██╔════╝ ┃                #
#                ┃  ███████║██║   ██║██████╔╝███████║█████╗   ┃                #
#                ┃  ██╔══██║██║   ██║██╔══██╗██╔══██║██╔══╝   ┃                #
#                ┃  ██║  ██║╚██████╔╝██║  ██║██║  ██║███████╗ ┃                #
#                ┃  ╚═╝  ╚═╝ ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝╚══════╝ ┃                #
#                ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛                #
#                                                                              #
#                         Distributed Systems Runtime                          #
#                                                                              #
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ #
#                                                                              #
#   Licensed under the Apache License, Version 2.0 (the "License");            #
#   you may not use this file except in compliance with the License.           #
#   You may obtain headers-check copy of the License at                        #
#                                                                              #
#       http://www.apache.org/licenses/LICENSE-2.0                             #
#                                                                              #
#   Unless required by applicable law or agreed to in writing, software        #
#   distributed under the License is distributed on an "AS IS" BASIS,          #
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   #
#   See the License for the specific language governing permissions and        #
#   limitations under the License.                                             #                                                                             #
#                                                                              #
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ #

# This script assumes running from the top level directory within a Makefile

. hack/headers-files-to-check

status=0

echo ""
echo ""
echo " [ Checking Scripts ] ==========================================================================================="


### Check Scripts
for SCRIPT in $SCRIPTS; do
    # Bypass files here
    if [ "$SCRIPT" == "ignore.me" ]; then
        continue
    fi

    # Replace the actual year with DATE so we can ignore the year when checking for the license header.
    HEADER=$(head -n 30 $SCRIPT | sed -E -e 's/Copyright © [0-9]+/Copyright © DATE/')
    if [ "$HEADER" != "$EXPECTEDSCRIPT" ]; then
      echo "  -> [FAILED SCRIPT FILE] Invalid header: $SCRIPT"
      STATUS=1
    fi
done

echo " [ Checking Source Code ] ======================================================================================="


### Check Source Files
for SOURCE in $SOURCES; do

    # Bypass files here
    if [ "$SOURCE" == "ignore.me" ]; then
        continue
    fi

    # Replace the actual year with DATE so we can ignore the year when checking for the license header.
    HEADER=$(head -n 30 $SOURCE | sed -E -e 's/Copyright © [0-9]+/Copyright © DATE/')
    if [ "$HEADER" != "$EXPECTEDSOURCE" ]; then
      echo "  -> [FAILED SOURCE FILE] Invalid header: $SOURCE"
      STATUS=1
    fi

done

echo " [ Checks Complete ] ============================================================================================"
echo ""
echo ""

exit $STATUS